CREATE TRIGGER T_CARD_PRICE
AFTER UPDATE OF price ON Card_Travel
REFERENCING NEW AS N OLD AS O
FOR EACH ROW WHEN ( N.price > 20 )
UPDATE Card_Travel
SET price = 20
WHERE N.LINEID = O.LINEID AND N.PASSENGEREGN = O.PASSENGEREGN AND lineID = 9041;

DROP TRIGGER T_CARD_PRICE;

UPDATE CARD_TRAVEL
SET price = price + 32
WHERE LINEID = 9041 AND PASSENGEREGN = '2610492833';

-- ---------------------------------------------------------------------------------------------------------------

CREATE TRIGGER T_WORKER
AFTER UPDATE OF salary ON WORKER
REFERENCING NEW AS N OLD AS O
FOR EACH ROW WHEN ( N.salary > 1500 AND N.WORKERTYPEID IN (SELECT ID FROM WORK_TYPE WHERE name = 'inspector' OR name = 'driver') )
UPDATE WORKER
SET salary = 1500
WHERE EGN = O.EGN;

DROP TRIGGER T_WORKER

UPDATE WORKER
SET salary = 2800
WHERE EGN = '9001148967';

UPDATE WORKER
SET salary = 2800
WHERE EGN = '1694381890';
